language: cpp
cache: ccache
dist: bionic
osx_image: xcode11
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
arch:
  - amd64
  - arm64

addons:
  homebrew:
    packages: ccache

env:
  matrix:
    - build_type=Release
    - build_type=Debug
    - build_type=Release build_shared=ON

script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_{C,CXX}_COMPILER_LAUNCHER=ccache -DCMAKE_BUILD_TYPE=${build_type:-Release} -DBUILD_SHARED_LIBS=${build_shared:-OFF}
  - make -j 8
  - make test
  - sudo make install

matrix:
  exclude:
    - os: osx
      compiler: gcc
    - os: osx
      arch: arm64
