image: Visual Studio 2017
configuration: Release
platform: x86_64

before_build: cmake .

build:
  project: xvc.sln
  
artifacts:
    - path: bin\Release\*.*
      name: $(APPVEYOR_PROJECT_NAME)

deploy:
  - provider: GitHub
    artifact: $(APPVEYOR_PROJECT_NAME)
    auth_token:
      secure: 'hY5Mk6KOwgQ97TzEBsM7Woqr1ZIm5QTvHg8EvxMV1x8j3wk/3mNBMqWFFbEIBK0i'
    prerelease: true
    on:
      appveyor_repo_tag: true
